# https://docs.github.com/en/actions

name: "Close"

on: # yamllint disable-line rule:truthy
  issues: null

jobs:
  close:
    name: "Close"

    runs-on: "ubuntu-latest"

#    if: >
#      github.event.name == 'issues' && (
#        github.event.action == 'opened' ||
#        github.event.action == 'reopened'
#      )

    steps:
      - name: "Determine issue number"
        uses: "actions/github-script@v6.3.1"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            if (context.eventName == 'issues') {
              core.exportVariable("ISSUE_NUMBER", context.payload.issue.number);

              return;
            }

            core.setFailed(`Unable to determine the issue number for event "${context.eventName}"`);

      - name: "Close issue"
        uses: "actions/github-script@v6.3.1"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            try {
              await github.rest.issues.update({
                issue_number: process.env.ISSUE_NUMBER,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "closed",
                state_reason:"not_planned",
              });
            } catch (error) {
              core.setFailed(error.message);
            }
