# https://docs.github.com/en/actions

name: "Context"

on: # yamllint disable-line rule:truthy
  check_run: null
  check_suite: null
  pull_request: null
  pull_request_target: null
  push: null
  workflow_run:
    types:
      - "completed"
    workflows:
      - "Integrate"

jobs:
  context:
    name: "Context"

    uses: './context-reusable.yaml@main'
