# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Deployment"

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "master"

jobs:
  create:
    name: "Create"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          ref: "${{ github.sha }}"

      - name: "Determine deployment parameters"
        run: |
          echo ::set-env name=DEPLOYMENT_REFERENCE::$(echo ${GITHUB_REF#refs/heads/})
          echo ::set-env name=DEPLOYMENT_SHA::$(git rev-parse --short --verify HEAD)

      - name: "Create deployment for production environment based on reference \"${{ env.DEPLOYMENT_REFERENCE }}\" and commit \"${{ env.DEPLOYMENT_SHA }}\""
        uses: "actions/github-script@0.8.0"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          previews: "ant-man"
          script: |
            const repository = context.repo

            github.repos.createDeployment({
              auto_inactive: true,
              auto_merge: false,
              environment: "production",
              owner: repository.owner,
              payload: {
                environmentUrl: "https://localheinz.com",
              },
              production_environment: true,
              ref: "${{ env.DEPLOYMENT_REFERENCE }}",
              repo: repository.repo,
              required_contexts: [],
              task: "deploy",
              transient_environment: false,
            })
