# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Deployment"

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "master"

jobs:
  create:
    name: "Create"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
          ref: "${{ github.sha }}"

      - name: "Determine name of branch to deploy"
        run: "echo ::set-env name=DEPLOY_BRANCH::$(echo ${GITHUB_REF#refs/heads/})"

      - name: "Determine SHA of commit to deploy"
        run: "echo ::set-env name=DEPLOY_SHA::$(git rev-parse --short --verify HEAD)"

      - name: "Create deployment for production environment based on branch \"${{ env.DEPLOY_BRANCH }}\" and commit \"${{ env.DEPLOY_SHA }}\""
        uses: "actions/github-script@0.8.0"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          previews: "ant-man"
          script: |
            github.repos.createDeployment({
              auto_inactive: true,
              auto_merge: false,
              environment: "production",
              owner: context.repo.owner,
              production_environment: true,
              ref: "${{ env.DEPLOY_SHA }}",
              repo: context.repo.repo,
              required_contexts: [],
              task: "deploy",
              transient_environment: false,
            })
