# https://docs.github.com/en/actions

name: "Deployment"

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - "closed"
      - "unlabeled"

env:
  DEPLOYMENT_ENVIRONMENT: "staging"

jobs:
  delete:
    name: "Delete"

    runs-on: "ubuntu-latest"

    if: "github.event.action == 'closed' || (github.event.action == 'unlabeled' && github.event.label.name == 'environment')"

    steps:
      - name: "Mark deployment for environment \"${{ env.DEPLOYMENT_ENVIRONMENT}}\" as inactive"
        uses: "actions/github-script@v3.0.0"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          previews: "ant-man"
          script: |
            const repository = context.repo

            const options = github.repos.listDeployments.endpoint.merge({
              environment: "${{ env.DEPLOYMENT_ENVIRONMENT }}",
              owner: repository.owner,
              per_page: 100,
              repo: repository.repo,
            })

            const previousDeployments = await github.paginate(options)

            for (const previousDeployment of previousDeployments) {
              if (previousDeployment.state == "inactive") {
                continue
              }

              await github.repos.createDeploymentStatus({
                deployment_id: previousDeployment.id,
                log_url: `https://github.com/${repository.owner}/${repository.repo}/commit/${previousDeployment.sha}/checks`,
                owner: repository.owner,
                repo: repository.repo,
                state: "inactive",
              })
            }
