# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Deployment"

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - "labeled"
      - "opened"
      - "reopened"
      - "synchronize"

jobs:
  create:
    name: "Create"

    runs-on: "ubuntu-latest"

    if: "((github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize') && contains(github.event.pull_request.labels.*.name, 'environment')) || (github.event.action == 'labeled' &&  github.event.label.name == 'environment')"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
          ref: "${{ github.head_ref }}"

      - name: "Determine SHA of commit to deploy"
        run: "echo ::set-env name=DEPLOY_SHA::$(git rev-parse --short --verify HEAD)"

      - name: "Create deployment for staging environment based on branch \"${{ github.head_ref }}\" and commit \"${{ env.DEPLOY_SHA }}\""
        uses: "actions/github-script@0.8.0"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          previews: "ant-man"
          script: |
            github.repos.createDeployment({
              auto_inactive: true,
              auto_merge: false,
              environment: "staging",
              owner: context.repo.owner,
              production_environment: false,
              ref: "${{ env.DEPLOY_SHA }}",
              repo: context.repo.repo,
              required_contexts: [],
              task: "deploy",
              transient_environment: true,
            })
