# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Deployment"

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - "closed"
      - "unlabeled"

env:
  DEPLOYMENT_ENVIRONMENT: "staging"

jobs:
  delete:
    name: "Delete"

    runs-on: "ubuntu-latest"

    if: "github.event.action == 'closed' || (github.event.action == 'unlabeled' && github.event.label.name == 'environment')"

    steps:
      - name: "Mark deployment for environment \"${{ env.DEPLOYMENT_ENVIRONMENT}}\" as inactive"
        uses: "actions/github-script@0.8.0"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          previews: "ant-man"
          script: |
            const repository = context.repo

            const { data: deployments } = await github.repos.listDeployments({
              environment: "${{ env.DEPLOYMENT_ENVIRONMENT }}",
              owner: repository.owner,
              repo: repository.repo,
            })

            deployments.forEach(deployment => {
              github.repos.createDeploymentStatus({
                deployment_id: deployment.id,
                log_url: `https://github.com/${repository.owner}/${repository.repo}/commit/${deployment.sha}/checks`,
                owner: repository.owner,
                repo: repository.repo,
                state: "inactive",
              })
            })
