# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "System"

on: # yamllint disable-line rule:truthy
  - "push"

jobs:
  js:
    name: "JS"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Show node version"
        run: "node --version"

      - name: "Show npm version"
        run: "npm --version"

      - name: "Show yarn version"
        run: "yarn --version"

  php:
    name: "PHP"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-binary:
          - "php"
          - "php7.1"
          - "php7.2"
          - "php7.3"
          - "php7.4"

    steps:
      - name: "Show location of PHP binary"
        run: "which ${{ matrix.php-binary}}"

      - name: "Show version"
        run: "${{ matrix.php-binary}} -v"

      - name: "Show information"
        run: "${{ matrix.php-binary}} -i"

      - name: "Show extensions"
        run: "${{ matrix.php-binary}} -m"

  reference:
    name: "Reference"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.2"

      - name: "Is branch"
        if: "startsWith(github.ref, 'refs/heads/')"
        run: "echo \"Is branch\""

      - name: "Is main"
        if: "github.event_name == 'push' && github.ref == 'refs/heads/main'"
        run: "echo \"Is main\""

      - name: "Is pull request"
        if: "startsWith(github.ref, 'refs/pull/')"
        run: "echo \"Is pull request\""

      - name: "Is tag"
        if: "startsWith(github.ref, 'refs/tags/')"
        run: "echo \"Is tag\""

  ssh:
    name: "SSH"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Location of ssh-agent"
        run: "echo $(which ssh-agent)"
