# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Integrate"

on: # yamllint disable-line rule:truthy
  pull_request: null
  push:
    branches:
      - "master"

env:
  MIN_COVERED_MSI: 100
  MIN_MSI: 100
  REQUIRED_PHP_EXTENSIONS: "mbstring"

jobs:
  merge:
    name: "Merge"

    runs-on: "ubuntu-latest"

    steps:
      - name: "List comments"
        uses: "actions/github-script@0.8.0"
        if: "github.actor != 'ergebnis-bot'"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          previews: "comfort-fade"
          script: |
            const pullRequest = context.payload.pull_request
            const repository = context.repo

            const response = await github.pulls.listComments({
              owner: repository.owner,
              page: 1,
              per_page: 100,
              pull_number: pullRequest.number,
              repo: repository.repo,
              since: pullRequest.created_at,
            })

            console.log(response)
