# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Merge"

on: # yamllint disable-line rule:truthy
  check_suite: null

jobs:
  merge:
    name: "Merge"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Dump context"
        uses: "actions/github-script@0.8.0"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            console.log(context)
