# https://docs.github.com/en/actions

name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "**"

jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Create release"
        uses: "ncipollo/release-action@v1.13.0"
        with:
          generateReleaseNotes: true
          token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
