# https://docs.github.com/en/actions

name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "**"

jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Determine tag"
        run: "echo \"TAG_NAME=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"

      - name: "Generate release notes"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const pullRequest = context.payload.pull_request
            const repository = context.repo

            const releaseNotes  = await github.rest.repos.generateReleaseNotes({
              owner: repository.owner,
              repo: repository.repo,
              tag_name: '${{ env.TAG_NAME }}',
            });

            console.log(releaseNotes)

      - name: "Create release"
        uses: "actions/create-release@v1.1.4"
        env:
          GITHUB_TOKEN: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
        with:
          draft: false
          prerelease: false
          release_name: "${{ env.TAG_NAME }}"
          tag_name: "${{ env.TAG_NAME }}"
