# https://docs.github.com/en/actions

name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
    tags:
      - "**"

jobs:
  release-key:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Determine release tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"

      - name: "Create release"
        uses: "actions/github-script@v5"
        env:
          RELEASE_TAG: "0.7.28"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const repository = context.repo;

            response = await github.rest.repos.createRelease({
              draft: false,
              generate_release_notes: true,
              name: "${{ env.RELEASE_TAG }}",
              owner: repository.owner,
              prerelease: false,
              repo: repository.repo,
              tag_name: "${{ env.RELEASE_TAG }}",
            });

            console.log(response)
