# https://docs.github.com/en/actions

name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
    tags:
      - "**"

jobs:
  release-key:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Determine release tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"

      - name: "Determine release body"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const repository = context.repo;

            const response = await github.rest.repos.generateReleaseNotes({
              owner: repository.owner,
              repo: repository.repo,
              tag_name: "${{ env.RELEASE_TAG }}",
            });

            core.exportVariable("RELEASE_BODY", response.data.body);

      - name: "Escape release body"
        run: |
          RELEASE_BODY="${RELEASE_BODY//'%'/'%25'}"
          RELEASE_BODY="${RELEASE_BODY//$'\n'/'%0A'}"
          RELEASE_BODY="${RELEASE_BODY//$'\r'/'%0D'}"

          echo \"RELEASE_BODY=${RELEASE_BODY}\" >> $GITHUB_ENV"

      - name: "Create release"
        uses: "actions/github-script@v5"
        env:
          RELEASE_TAG: "0.7.25"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const repository = context.repo;

            await github.rest.repos.createRelease({
              body: "${{ env.RELEASE_BODY }}",
              draft: false,
              name: "${{ env.RELEASE_TAG }}",
              owner: repository.owner,
              prerelease: false,
              repo: repository.repo,
              tag_name: "${{ env.RELEASE_TAG }}",
            });
