# https://docs.github.com/en/actions

name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "**"

jobs:
  release:
    name: "Release"
    uses: './.github/workflows/release-resuable'
    with:
      secrets:
        WORKFLOW_TOKEN: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
