# https://docs.github.com/en/actions

name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "**"

jobs:
  release:
    name: "Release (Reusing)"
    uses: 'ergebnis/playground/.github/workflows/release-reusable.yaml@main'
    secrets:
      WORKFLOW_TOKEN: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
