# https://docs.github.com/en/actions

name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
    tags:
      - "**"

jobs:
  release-key:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Determine release tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"

      - name: "Create release"
        uses: "actions/github-script@v5"
        env:
          RELEASE_TAG: "0.7.29"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const repository = context.repo;

            response = await github.rest.repos.createRelease({
              draft: false,
              generate_release_notes: true,
              name: "${{ env.RELEASE_TAG }}",
              owner: repository.owner,
              prerelease: false,
              repo: repository.repo,
              tag_name: "${{ env.RELEASE_TAG }}",
            });

            core.exportVariable("RELEASE_ID", response.data.id)
            core.exportVariable("RELEASE_UPLOAD_URL", response.data.upload_url)

      - name: "Upload release assets"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const fs = require("fs");

            const repository = context.repo;

            await github.rest.repos.uploadReleaseAsset({
              data: fs.readFileSync("Makefile"),
              name: "Makefile",
              origin: "${{ env.RELEASE_UPLOAD_URL }}",
              owner: repository.owner,
              release_id: "${{ env.RELEASE_ID }}",
              repo: repository.repo,
            });

