name: "Triage"

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - "opened"
      - "synchronize"
      - "reopen"

jobs:
  label:
    name: "Label"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Add labels based on branch name"
        uses: "actions/github-script@v2.0.0"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const branchPrefixLabels = {
              feature: "enhancement",
              fix: "bug",
            }

            const pullRequest = context.payload.pull_request
            const repository = context.repo

            const branchName = pullRequest.head.ref

            const matches = branchName.match(new RegExp('^([^/]+)\/'));

            if (matches instanceof Array && branchPrefixLabels.hasOwnProperty(matches[1])) {
              const label = branchPrefixLabels[matches[1]]

              github.issues.addLabels({
                issue_number: pullRequest.number,
                labels: [
                  label
                ],
                owner: repository.owner,
                repo: repository.repo,
              });
            }

  close:
    name: "Close"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Close pull request based on authors"
        uses: "actions/github-script@v2.0.1"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const authors = [
              "localheinz",
            ]

            const pullRequest = context.payload.pull_request
            const repository = context.repo

            const author = pullRequest.user.login;

            if (authors.includes(author)) {
              github.issues.createComment({
                owner: repository.owner,
                issue_number: pullRequest.number,
                repo: repository.repo,
                body: "I'm sorry, @" + author + ".I'm afraid you can't do that."
              });

              github.pulls.update({
                owner: repository.owner,
                pull_number: pullRequest.number,
                repo: repository.repo,
                state: "closed",
              });


            }
