# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Triage"

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - "opened"
      - "synchronize"

jobs:
  label:
    name: "Label"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Add labels based on branch name"
        uses: "actions/github-script@0.8.0"
        if: "github.event.action == 'opened'"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          previews: "ant-man"
          script: |
            const branchPrefixLabels = {
              feature: "enhancement",
              fix: "bug",
            }

            const pullRequest = context.payload.pull_request
            const repository = context.repo

            const branchName = pullRequest.head.ref

            const matches = branchName.match(new RegExp('^([^/]+)\/'));

            if (matches instanceof Array && branchPrefixLabels.hasOwnProperty(matches[1])) {
              const label = branchPrefixLabels[matches[1]]

              github.issues.addLabels({
                issue_number: pullRequest.number,
                labels: [
                  label
                ],
                owner: repository.owner,
                repo: repository.repo,
              });
            }

      - name: "Add labels based on commit message"
        if: "github.event.action == 'synchronize'"
        uses: "actions/github-script@0.8.0"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const pullRequest = context.payload.pull_request
            const repository = context.repo

            const commits = await github.repos.listCommits({
              owner: repository.owner,
              per_page: 10,
              pull_number: pullRequest.number,
              repo: repository.repo,
            })

            console.log(commits)
